### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by regehr** [DRMacIver/structureshrink#3]
I'm getting a crash running latest structureshrink in --principal mode, does this ring any bells? I can teach you to reproduce this but it's going to be a pain since you need to build a pretty old version of LLVM.

```
Initial example: 2200300 bytes , labelled 0
Shrink 2: Label 0 now 1970716 bytes (deleted 229584)
Shrink 3: Discovered new label 255 with 0 bytes
Shrinking for label 0 from 1970716 bytes
Shrink 4: Discovered new label 'timeout' with 1968478 bytes
Shrink 5: Label 'timeout' now 1942207 bytes (deleted 26271)
Shrinking for label 0 from 1970716 bytes
Traceback (most recent call last):
  File "/usr/local/bin/structureshrink", line 9, in <module>
    load_entry_point('structureshrink==0.0.1', 'console_scripts', 'structureshrink')()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/structureshrink-0.0.1-py3.4.egg/structureshrink/__main__.py", line 265, in shrinker
    shrinker.shrink()
  File "/usr/local/lib/python3.4/dist-packages/structureshrink-0.0.1-py3.4.egg/structureshrink/shrinker.py", line 241, in shrink
    for ngram in self.__suitable_ngrams(label):
  File "/usr/local/lib/python3.4/dist-packages/structureshrink-0.0.1-py3.4.egg/structureshrink/shrinker.py", line 121, in __suitable_ngrams
    found_ngrams = ngrams(self.best[label])
  File "/usr/local/lib/python3.4/dist-packages/structureshrink-0.0.1-py3.4.egg/structureshrink/shrinker.py", line 353, in ngrams
    len(new_grams_to_indices[list(seen)[0]]) >= len(ng) + 1
KeyError: b' \n'
```

**Comment by DRMacIver** [comment]
Hmm. I've not seen that before. Weird. 

By a complete coincidence I happen to have just removed that line of code, so I might just have fixed this by accident. Try pulling latest master and see if it fixes it?

**Comment by DRMacIver** [comment]
Ugh, sorry, wait one second. I also pushed something broken.

**Comment by DRMacIver** [comment]
OK. _Now_ pull and try again. :-)

Sorry you're not exactly experiencing my finest work here.

**Comment by regehr** [comment]
Testing now with a super tough reduction where C-Reduce can barely get it below 1 KB. No crash so far.
